steps:
# Build the container targetting the test stage
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--network=cloudbuild',
    '--target', 'testbuild',
    '-t', 'gcr.io/luabase/luabase-py-test',
    '.'
  ]
  env: ['DOCKER_BUILDKIT=1']
